#+title: Ateliers #BlueHats
#+category: BLH

* 2023
  :PROPERTIES:
  :ID:       320a0c70-7e0d-4244-b756-ee99bf34e8b5
  :END:

** 7 juillet : Présentation des évolutions d'atlaSanté
   :PROPERTIES:
   :ID:       6d2d60a5-bb3d-420e-a81b-347cfd1c39dc
   :END:

/Intervenante : Stéphanie Dauthel./

AtlaSanté est, depuis 10 ans, le portail d'informations géographiques
mutualisé des Agences régionales de Santé et du ministère de la santé
et de la prévention. Véritable outil d'aide à la décision en matière
de santé et d'environnement pour un territoire donné, il met à
disposition de ses utilisateurs des cartes thématiques basées sur
Prodige, des observatoires géostatistiques et des portraits de
territoires basés sur Géoclip pour ainsi valoriser les données
géographiques socio-sanitaires et d'environnement.

** 23 juin : Présentation de [[https://github.com/codegouvfr/react-dsfr][react-dsfr]]
   :PROPERTIES:
   :ID:       53949cb1-0452-41a9-98e1-fd375aedd56b
   :END:
** 9 juin : Présentation de l'interface d'explicabilité de Catala
   :PROPERTIES:
   :ID:       5a9f0f88-f656-47df-9972-545640fc425f
   :END:
** 26 mai : libre
   :PROPERTIES:
   :ID:       666c897c-6a3a-49b1-bfbe-ad5660688390
   :END:

** 19 mai : Implémentations libres pour le metaverse
   :PROPERTIES:
   :ID:       d85557ad-1ca2-483d-b726-08063226d9fe
   :END:

/Intervenant : Fabien Benetou/

On entend parler de metaverse de plus en plus, autant au niveau
commercial que plus récemment au niveau legislatif.  Derrière ce terme
abstrait il existe déjà des implémentations et en particuler des
implémentations libres basées sur des standards intéropérables.  Le
but de cet atelier et de découvrir lesquelles, avec quels avantages et
limites, et comment les mettre en place.

Mozilla Hubs : solution complète, clef en main, libre et gérée par
Mozilla.

Networked AFrame : couche uniquement réseau pour qu'un objet en 3D, et
potentiellement la voix et la vidéo, puissent s'afficher de façon
cohérente sur les ordinateurs ou casques VR et AR de tous les
participants.

ImmerSpace : couche uniquement fédératrice, gestion de profils avec
des méta-données associées, permettant de connecter plusieurs serveurs
avec des implémentations indépendantes par exemple Mozilla Hubs,
Networked AFrames, FrameVR, etc.

Dédié à tout public pour l'introduction, en particulier
l'architecture ; pour l'implémentation une maîtrise du /frontend/
(JavaScript) et du /backend/ (NodeJS, /containers/ par ex. Docker)
nécessaire.

Ces outils sont utilisés en test par l'équipe innovation du Parlement
Européen.

